services:
  - type: web
    name: coffee-duty
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src app:app"
    plan: free
